# Generated by Django 5.2.8 on 2026-03-19 20:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0008_remove_appointment_checked_in_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField(default=django.utils.timezone.now)),
                ('day_number', models.PositiveIntegerField(help_text='Day 0 = therapy day, Day 1-7 = daily follow-ups')),
                ('is_therapy_day', models.BooleanField(default=False, help_text='True if this is the day of therapy')),
                ('pain_level', models.IntegerField(default=0, help_text='Pain level (0-100, 0=no pain, 100=severe pain)')),
                ('sleep_quality', models.IntegerField(default=0, help_text='Sleep quality (0-100, 0=poor, 100=excellent)')),
                ('stress_level', models.IntegerField(default=0, help_text='Stress level (0-100, 0=no stress, 100=extreme stress)')),
                ('energy_level', models.IntegerField(default=0, help_text='Energy level (0-100, 0=no energy, 100=high energy)')),
                ('digestion_quality', models.IntegerField(default=0, help_text='Digestion quality (0-100, 0=poor, 100=excellent)')),
                ('mood_level', models.IntegerField(default=0, help_text='Mood level (0-100, 0=very low, 100=excellent)')),
                ('notes', models.TextField(blank=True, help_text='Additional observations or notes')),
                ('symptoms', models.JSONField(blank=True, default=list, help_text='List of symptoms experienced')),
                ('medications_taken', models.JSONField(blank=True, default=list, help_text='List of medications taken')),
                ('agni_score', models.IntegerField(blank=True, help_text='Digestive fire score (0-100)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progress_entries', to='appointments.appointment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_entries', to=settings.AUTH_USER_MODEL)),
                ('treatment_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progress_entries', to='appointments.treatmentplan')),
            ],
            options={
                'ordering': ['-entry_date', '-day_number'],
                'indexes': [models.Index(fields=['patient', 'entry_date'], name='progress_pr_patient_8aeec2_idx'), models.Index(fields=['appointment', 'day_number'], name='progress_pr_appoint_00f032_idx')],
                'unique_together': {('patient', 'appointment', 'day_number')},
            },
        ),
    ]
