# Generated by Django 5.2.8 on 2026-03-19 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_emailotp_temp_phone_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('temp_username', models.CharField(blank=True, max_length=150, null=True)),
                ('temp_password', models.CharField(blank=True, max_length=200, null=True)),
                ('temp_role', models.CharField(blank=True, max_length=50, null=True)),
                ('temp_phone', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='EmailOTP',
        ),
    ]
