# Generated by Django 5.2.8 on 2026-03-19 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_remove_appointment_checked_in_at_and_more'),
        ('clinic', '0005_therapistassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapistassignment',
            name='treatment_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='appointments.treatmentplan'),
        ),
    ]
